
## Documentation

defaults:
  run:
    shell: bash
    working-directory: docusaurus-site/


name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: docusaurus-site

      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docusaurus-site/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4